openapi: 3.0.3
info:
  title: CTC Traders Test Support
  contact: {}
  version: '1.0'
  description: |
    # Overview
    Use the CTC Traders Test Support API to inject departure and arrival movement notifications as if they have come from a customs office of departure
    or destination through the New Computerised Transit System (NCTS).
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
paths:
  /test/customs/transits/movements/arrivals/{arrivalId}/messages:
    post:
      tags:
      - Arrivals
      summary: Inject a fake NCTS arrival message
      description: >
        Inject a message type into the test NCTS database for a given arrival Movement.
      operationId: postFakeNCTSArrivalMessage
      parameters:
        - $ref: '#/components/parameters/contentTypeHeader'
        - in: path
          name: arrivalId
          description: The arrival ID specifying the arrival to return.
          required: true
          style: simple
          schema:
            type: string
            example: '1'
      requestBody:
        description: JSON with message type
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/TestCustomsTransitsMovementsArrivalsMessagesRequest'
              - description: JSON with message type
                example:
                  message:
                    messageType: IEXXX
            example:
              message:
                messageType: IEXXX
        required: true
      responses:
        '201':
          description: A successful test message injection response.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/TestCustomsTransitsMovementsArrivalsMessagesResponse'
                - description: JSON payload
                  example:
                    _links:
                      self:
                        href: /customs/transits/movements/arrivals/1/messages/2
                      arrival:
                        href: /customs/transits/movements/arrivals/1
                    arrivalId: '1'
                    messageId: '2'
                    messageType: IEXXX
                    body: <CCXXX>...</CCXXX>
              example:
                _links:
                  self:
                    href: /customs/transits/movements/arrivals/1/messages/2
                  arrival:
                    href: /customs/transits/movements/arrivals/1
                arrivalId: '1'
                messageId: '2'
                messageType: IEXXX
                body: <CCXXX>...</CCXXX>
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - description: The supplied payload was invalid.
                    example:
                      statusCode: 400
              example:
                statusCode: 400
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - description: Supplied arrival not found or does not exist or has been archived or is not available to the EORI number.
                    example:
                      statusCode: 404
              example:
                statusCode: 404
      deprecated: false
      security:
        - userRestricted:
            - common-transit-convention-traders-test-support
  /test/customs/transits/movements/departures/{departureId}/messages:
    post:
      tags:
      - Departures
      summary: Inject a fake NCTS departure message
      description: >
        Inject a message type into the test NCTS database for a given departure.
      operationId: postFakeNCTSDepartureMessage
      parameters:
        - $ref: '#/components/parameters/contentTypeHeader'
        - in: path
          name: departureId
          description: The departure ID specifying the departure to return.
          required: true
          style: simple
          schema:
            type: string
            example: '1'
      requestBody:
        description: JSON with message type
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/TestCustomsTransitsMovementsDeparturesMessagesRequest'
              - description: JSON with message type
                example:
                  message:
                    messageType: IEXXX
            example:
              message:
                messageType: IEXXX
        required: true
      responses:
        '201':
          description: A successful test message injection response.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/TestCustomsTransitsMovementsDeparturesMessagesResponse'
                - description: JSON payload
                  example:
                    _links:
                      self:
                        href: /customs/transits/movements/departures/1/messages/2
                      departure:
                        href: /customs/transits/movements/departures/1
                    departureId: '1'
                    messageId: '2'
                    messageType: IEXXX
                    body: <CCXXX>...</CCXXX>
              example:
                _links:
                  self:
                    href: /customs/transits/movements/departures/1/messages/2
                  departure:
                    href: /customs/transits/movements/departures/1
                departureId: '1'
                messageId: '2'
                messageType: IEXXX
                body: <CCXXX>...</CCXXX>
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - description: The supplied payload was invalid.
                    example:
                      statusCode: 400
              example:
                statusCode: 400
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - description: Supplied departure not found or does not exist or has been archived or is not available to the EORI number.
                    example:
                      statusCode: 404
              example:
                statusCode: 404
      deprecated: false
      security:
        - userRestricted:
            - common-transit-convention-traders-test-support

components:
  schemas:
    errorResponse:
      title: errorResponse
      required:
        - statusCode
      type: object
      properties:
        statusCode:
          type: integer
    Arrival:
      title: Arrival
      required:
      - href
      type: object
      properties:
        href:
          type: string
      example:
        href: /customs/transits/movements/arrivals/1
    Departure:
      title: Departure
      required:
      - href
      type: object
      properties:
        href:
          type: string
      example:
        href: /customs/transits/movements/departures/1
    Links:
      title: Links
      required:
      - self
      - arrival
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Self'
        arrival:
          $ref: '#/components/schemas/Arrival'
      example:
        self:
          href: /customs/transits/movements/arrivals/1/messages/2
        arrival:
          href: /customs/transits/movements/arrivals/1
    Links1:
      title: Links1
      required:
      - self
      - departure
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Self'
        departure:
          $ref: '#/components/schemas/Departure'
      example:
        self:
          href: /customs/transits/movements/departures/1/messages/2
        departure:
          href: /customs/transits/movements/departures/1
    Message:
      title: Message
      required:
      - messageType
      type: object
      properties:
        messageType:
          type: string
      example:
        messageType: IEXXX
    Self:
      title: Self
      required:
      - href
      type: object
      properties:
        href:
          type: string
      example:
        href: /customs/transits/movements/arrivals/1/messages/2
    TestCustomsTransitsMovementsArrivalsMessagesRequest:
      title: TestCustomsTransitsMovementsArrivalsMessagesRequest
      required:
      - message
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
      example:
        message:
          messageType: IEXXX
    TestCustomsTransitsMovementsArrivalsMessagesResponse:
      title: TestCustomsTransitsMovementsArrivalsMessagesResponse
      required:
      - _links
      - arrivalId
      - messageId
      - messageType
      - body
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/Links'
        arrivalId:
          type: string
        messageId:
          type: string
        messageType:
          type: string
        body:
          type: string
      example:
        _links:
          self:
            href: /customs/transits/movements/arrivals/1/messages/2
          arrival:
            href: /customs/transits/movements/arrivals/1
        arrivalId: '1'
        messageId: '2'
        messageType: IEXXX
        body: <CCXXX>...</CCXXX>
    TestCustomsTransitsMovementsDeparturesMessagesRequest:
      title: TestCustomsTransitsMovementsDeparturesMessagesRequest
      required:
      - message
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
      example:
        message:
          messageType: IEXXX
    TestCustomsTransitsMovementsDeparturesMessagesResponse:
      title: TestCustomsTransitsMovementsDeparturesMessagesResponse
      required:
      - _links
      - departureId
      - messageId
      - messageType
      - body
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/Links1'
        departureId:
          type: string
        messageId:
          type: string
        messageType:
          type: string
        body:
          type: string
      example:
        _links:
          self:
            href: /customs/transits/movements/departures/1/messages/2
          departure:
            href: /customs/transits/movements/departures/1
        departureId: '1'
        messageId: '2'
        messageType: IEXXX
        body: <CCXXX>...</CCXXX>
  parameters:
    contentTypeHeader:
      name: Content-Type
      in: header
      description: The media type of the request body.
      schema:
        type: string
        enum:
          - application/json
      required: true
  securitySchemes:
    userRestricted:
      type: oauth2
      description: >-
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using
        an OAuth 2.0 Bearer Token in the AUTHORIZATION header. See
        https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints
        for details.
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.service.hmrc.gov.uk/oauth/authorize'
          tokenUrl: 'https://api.service.hmrc.gov.uk/oauth/token'
          refreshUrl: 'https://api.service.hmrc.gov.uk/oauth/refresh'
          scopes:
            common-transit-convention-traders-test-support: Access all aspects of ctc api test support.
